import React, { useState } from 'react';
import { useTask } from '../context/TaskContext';
import {
  Sparkles,
  Bot,
  Wand2,
  CheckCircle2,
  PlusCircle,
  X,
  AlertCircle,
  Clock,
  Layers,
  ArrowRight,
  ListTodo
} from 'lucide-react';

export const AICopilotModal = ({ isOpen, onClose }) => {
  const { bulkCreateTasks, tasks } = useTask();
  const [goalInput, setGoalInput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedSubtasks, setGeneratedSubtasks] = useState([]);
  const [aiAdvice, setAiAdvice] = useState('');
  const [addedSuccess, setAddedSuccess] = useState(false);

  if (!isOpen) return null;

  const handleGenerateAI = () => {
    if (!goalInput.trim()) return;

    setIsGenerating(true);
    setGeneratedSubtasks([]);
    setAiAdvice('');
    setAddedSuccess(false);

    setTimeout(() => {
      const goal = goalInput.trim();
      let subtasks = [];
      let advice = '';

      if (goal.toLowerCase().includes('security') || goal.toLowerCase().includes('owasp') || goal.toLowerCase().includes('audit')) {
        subtasks = [
          { title: `${goal}: Audit JWT token encryption & expiration`, priority: 'urgent', category: 'Security', estimatedMinutes: 45 },
          { title: `${goal}: Sanitize MongoDB inputs against NoSQL injections`, priority: 'high', category: 'Backend', estimatedMinutes: 60 },
          { title: `${goal}: Configure Helmet HTTP security headers`, priority: 'medium', category: 'Security', estimatedMinutes: 30 },
          { title: `${goal}: Implement Express rate-limiting middleware`, priority: 'high', category: 'Backend', estimatedMinutes: 40 }
        ];
        advice = 'AI Advice: Security audits should prioritize rate-limiting and input sanitization first to prevent automated brute-force attacks.';
      } else if (goal.toLowerCase().includes('mobile') || goal.toLowerCase().includes('design') || goal.toLowerCase().includes('ui')) {
        subtasks = [
          { title: `${goal}: Wireframe responsive touch breakpoints`, priority: 'medium', category: 'Design', estimatedMinutes: 30 },
          { title: `${goal}: Implement off-canvas drawer navigation for mobile`, priority: 'urgent', category: 'Frontend', estimatedMinutes: 90 },
          { title: `${goal}: Optimize touch drag/crop gestures for mobile`, priority: 'high', category: 'Frontend', estimatedMinutes: 60 },
          { title: `${goal}: Conduct cross-device viewport testing`, priority: 'low', category: 'QA', estimatedMinutes: 45 }
        ];
        advice = 'AI Advice: Mobile UX optimization should focus heavily on off-canvas drawers and touch-friendly target sizes (min 44px).';
      } else {
        subtasks = [
          { title: `${goal}: Requirements analysis & technical scoping`, priority: 'medium', category: 'Planning', estimatedMinutes: 30 },
          { title: `${goal}: Core architecture setup & API endpoint creation`, priority: 'high', category: 'Engineering', estimatedMinutes: 90 },
          { title: `${goal}: UI component implementation & state wiring`, priority: 'high', category: 'Frontend', estimatedMinutes: 75 },
          { title: `${goal}: Integration testing & documentation update`, priority: 'medium', category: 'QA', estimatedMinutes: 45 }
        ];
        advice = `AI Advice: Successfully broken down "${goal}" into 4 structured, high-efficiency subtasks ready for execution.`;
      }

      setGeneratedSubtasks(subtasks);
      setAiAdvice(advice);
      setIsGenerating(false);
    }, 1200);
  };

  const handleAddTasksToWorkspace = async () => {
    if (generatedSubtasks.length === 0) return;

    const formattedTasks = generatedSubtasks.map(item => ({
      title: item.title,
      description: `Auto-generated by AI Copilot for goal: "${goalInput}"`,
      priority: item.priority,
      category: item.category,
      status: 'todo',
      dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
    }));

    try {
      await bulkCreateTasks(formattedTasks);
      setAddedSuccess(true);
      setTimeout(() => {
        setAddedSuccess(false);
        onClose();
        setGoalInput('');
        setGeneratedSubtasks([]);
      }, 1500);
    } catch (err) {
      console.error('Failed to add AI tasks:', err);
    }
  };

  return (
    <div style={{
      position: 'fixed',
      top: 0, left: 0, right: 0, bottom: 0,
      background: 'rgba(5, 8, 16, 0.88)',
      backdropFilter: 'blur(12px)',
      WebkitBackdropFilter: 'blur(12px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1100,
      padding: '1rem'
    }}>
      <div className="glass-panel animate-fade-in" style={{
        width: '100%',
        maxWidth: '620px',
        maxHeight: '90vh',
        borderRadius: 'var(--radius-xl)',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
        boxShadow: '0 30px 60px -15px rgba(0, 0, 0, 0.8), var(--shadow-glow)',
        border: '1px solid var(--border-glow)'
      }}>
        {/* Modal Header */}
        <div style={{
          padding: '1.25rem 1.5rem',
          borderBottom: '1px solid var(--border-subtle)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          background: 'rgba(99, 102, 241, 0.06)'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.65rem' }}>
            <div style={{
              width: '36px', height: '36px',
              borderRadius: '10px',
              background: 'var(--gradient-primary)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              boxShadow: 'var(--shadow-glow)'
            }}>
              <Bot size={22} color="#fff" />
            </div>
            <div>
              <h3 style={{ fontSize: '1.15rem', fontWeight: '800', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                AI Task Copilot & Generator <Sparkles size={16} color="#fbbf24" />
              </h3>
              <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>
                Type any project objective to auto-generate subtasks with AI.
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', padding: '0.35rem' }}
          >
            <X size={20} />
          </button>
        </div>

        {/* Modal Content */}
        <div style={{ padding: '1.5rem', overflowY: 'auto', flex: 1 }}>
          {/* Input Goal Area */}
          <div style={{ marginBottom: '1.25rem' }}>
            <label className="form-label" style={{ fontSize: '0.875rem', fontWeight: '700' }}>
              What high-level objective would you like AI to break down?
            </label>
            <div style={{ display: 'flex', gap: '0.6rem', marginTop: '0.45rem' }}>
              <input
                type="text"
                className="form-input"
                placeholder="e.g. Implement OWASP Security Audit and Rate Limiting..."
                value={goalInput}
                onChange={(e) => setGoalInput(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleGenerateAI()}
                style={{ flex: 1 }}
              />
              <button
                type="button"
                onClick={handleGenerateAI}
                disabled={isGenerating || !goalInput.trim()}
                className="btn btn-primary"
                style={{ padding: '0.7rem 1.25rem', gap: '0.45rem', whiteSpace: 'nowrap' }}
              >
                {isGenerating ? (
                  <><Wand2 className="spinner" size={16} /> Generating...</>
                ) : (
                  <><Wand2 size={16} /> Auto-Breakdown</>
                )}
              </button>
            </div>
          </div>

          {/* Quick Prompt Suggestions */}
          <div style={{ display: 'flex', gap: '0.4rem', flexWrap: 'wrap', marginBottom: '1.5rem' }}>
            <span style={{ fontSize: '0.75rem', color: 'var(--text-dim)', alignSelf: 'center' }}>Try:</span>
            {[
              'OWASP Security Audit',
              'Mobile Off-Canvas Drawer',
              'MongoDB Atlas Backend API',
              'Design System Dark Mode'
            ].map(prompt => (
              <button
                key={prompt}
                type="button"
                onClick={() => setGoalInput(prompt)}
                style={{
                  fontSize: '0.75rem',
                  padding: '0.25rem 0.65rem',
                  borderRadius: '12px',
                  background: 'rgba(255,255,255,0.05)',
                  border: '1px solid var(--border-subtle)',
                  color: 'var(--text-muted)',
                  cursor: 'pointer'
                }}
              >
                + {prompt}
              </button>
            ))}
          </div>

          {addedSuccess && (
            <div style={{
              padding: '0.9rem 1.1rem',
              borderRadius: 'var(--radius-md)',
              background: 'rgba(16, 185, 129, 0.15)',
              border: '1px solid rgba(16, 185, 129, 0.3)',
              color: '#34d399',
              marginBottom: '1.25rem',
              display: 'flex',
              alignItems: 'center',
              gap: '0.6rem',
              fontSize: '0.875rem'
            }}>
              <CheckCircle2 size={18} /> Generated AI subtasks added to your workspace!
            </div>
          )}

          {/* Generated Subtasks Preview */}
          {generatedSubtasks.length > 0 && (
            <div>
              {aiAdvice && (
                <div style={{
                  padding: '0.85rem 1rem',
                  borderRadius: 'var(--radius-md)',
                  background: 'rgba(99, 102, 241, 0.1)',
                  border: '1px solid rgba(99, 102, 241, 0.25)',
                  color: '#818cf8',
                  fontSize: '0.825rem',
                  marginBottom: '1.25rem',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.5rem'
                }}>
                  <Sparkles size={16} flexShrink={0} /> {aiAdvice}
                </div>
              )}

              <h4 style={{ fontSize: '0.9rem', fontWeight: '700', color: 'var(--text-muted)', marginBottom: '0.75rem' }}>
                AI GENERATED ACTION ITEMS ({generatedSubtasks.length})
              </h4>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.65rem', marginBottom: '1.5rem' }}>
                {generatedSubtasks.map((task, idx) => (
                  <div
                    key={idx}
                    style={{
                      padding: '0.85rem 1rem',
                      borderRadius: 'var(--radius-md)',
                      background: 'rgba(255,255,255,0.03)',
                      border: '1px solid var(--border-subtle)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      gap: '0.75rem'
                    }}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.65rem' }}>
                      <ListTodo size={16} color="var(--accent-primary)" />
                      <div>
                        <p style={{ fontSize: '0.875rem', fontWeight: '600' }}>{task.title}</p>
                        <p style={{ fontSize: '0.75rem', color: 'var(--text-dim)' }}>
                          Category: {task.category} • ~{task.estimatedMinutes} mins
                        </p>
                      </div>
                    </div>
                    <span className={`badge badge-${task.priority}`} style={{ fontSize: '0.65rem' }}>
                      {task.priority}
                    </span>
                  </div>
                ))}
              </div>

              <button
                type="button"
                onClick={handleAddTasksToWorkspace}
                className="btn btn-primary"
                style={{ width: '100%', padding: '0.75rem', justifyContent: 'center', fontWeight: '700', gap: '0.5rem' }}
              >
                <PlusCircle size={18} /> Add All {generatedSubtasks.length} Subtasks to Workspace
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
